# Generated by Django 5.2.11 on 2026-03-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_editora_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
